// <auto-generated />
using System;
using EmreGeydirenler_Lab2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmreGeydirenler_Lab2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402095646_FinalLab3Cleanup")]
    partial class FinalLab3Cleanup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.AccountSetting", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveEmailAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.ToTable("AccountSettings");

                    b.HasData(
                        new
                        {
                            CustomerId = 2001,
                            ReceiveEmailAlerts = true,
                            TwoFactorEnabled = true
                        },
                        new
                        {
                            CustomerId = 2002,
                            ReceiveEmailAlerts = true,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            CustomerId = 2003,
                            ReceiveEmailAlerts = false,
                            TwoFactorEnabled = true
                        },
                        new
                        {
                            CustomerId = 2004,
                            ReceiveEmailAlerts = true,
                            TwoFactorEnabled = false
                        },
                        new
                        {
                            CustomerId = 2005,
                            ReceiveEmailAlerts = true,
                            TwoFactorEnabled = true
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditTrails");

                    b.HasData(
                        new
                        {
                            Id = 6001,
                            ActionDescription = "Created the Growth plan campaign settings.",
                            IPAddress = "10.10.1.11",
                            Timestamp = new DateTime(2026, 3, 10, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1001
                        },
                        new
                        {
                            Id = 6002,
                            ActionDescription = "Reviewed invoice disputes for enterprise clients.",
                            IPAddress = "10.10.1.12",
                            Timestamp = new DateTime(2026, 3, 12, 11, 45, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1002
                        },
                        new
                        {
                            Id = 6003,
                            ActionDescription = "Updated security rules for admin sign-in.",
                            IPAddress = "10.10.1.13",
                            Timestamp = new DateTime(2026, 3, 14, 14, 5, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1003
                        },
                        new
                        {
                            Id = 6004,
                            ActionDescription = "Approved plan pricing adjustment request.",
                            IPAddress = "10.10.1.14",
                            Timestamp = new DateTime(2026, 3, 16, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1004
                        },
                        new
                        {
                            Id = 6005,
                            ActionDescription = "Published monthly usage analytics report.",
                            IPAddress = "10.10.1.15",
                            Timestamp = new DateTime(2026, 3, 18, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 1005
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.BaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaseUsers");

                    b.HasDiscriminator<string>("UserType").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");

                    b.HasData(
                        new
                        {
                            Id = 4001,
                            CustomerId = 2001,
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            IssueDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 79m
                        },
                        new
                        {
                            Id = 4002,
                            CustomerId = 2002,
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            IssueDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 149m
                        },
                        new
                        {
                            Id = 4003,
                            CustomerId = 2003,
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = false,
                            IssueDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 299m
                        },
                        new
                        {
                            Id = 4004,
                            CustomerId = 2004,
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = true,
                            IssueDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 29m
                        },
                        new
                        {
                            Id = 4005,
                            CustomerId = 2005,
                            DueDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsPaid = false,
                            IssueDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TotalAmount = 599m
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Automates recurring invoices, payment reminders, and ledger exports.",
                            ModuleName = "Billing Automation"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tracks leads, deal stages, and customer lifecycle activities.",
                            ModuleName = "CRM Pipeline"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Designs approval flows and task routing for internal processes.",
                            ModuleName = "Workflow Engine"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Provides KPI dashboards, cohort analysis, and custom reporting.",
                            ModuleName = "Analytics Hub"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Manages role-based permissions, SSO integration, and audit visibility.",
                            ModuleName = "Access Control"
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.PlanModule", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("PlanModules");

                    b.HasData(
                        new
                        {
                            PlanId = 1,
                            ModuleId = 1
                        },
                        new
                        {
                            PlanId = 1,
                            ModuleId = 5
                        },
                        new
                        {
                            PlanId = 2,
                            ModuleId = 1
                        },
                        new
                        {
                            PlanId = 2,
                            ModuleId = 2
                        },
                        new
                        {
                            PlanId = 2,
                            ModuleId = 5
                        },
                        new
                        {
                            PlanId = 3,
                            ModuleId = 1
                        },
                        new
                        {
                            PlanId = 3,
                            ModuleId = 2
                        },
                        new
                        {
                            PlanId = 3,
                            ModuleId = 3
                        },
                        new
                        {
                            PlanId = 3,
                            ModuleId = 5
                        },
                        new
                        {
                            PlanId = 4,
                            ModuleId = 1
                        },
                        new
                        {
                            PlanId = 4,
                            ModuleId = 2
                        },
                        new
                        {
                            PlanId = 4,
                            ModuleId = 3
                        },
                        new
                        {
                            PlanId = 4,
                            ModuleId = 4
                        },
                        new
                        {
                            PlanId = 4,
                            ModuleId = 5
                        },
                        new
                        {
                            PlanId = 5,
                            ModuleId = 1
                        },
                        new
                        {
                            PlanId = 5,
                            ModuleId = 2
                        },
                        new
                        {
                            PlanId = 5,
                            ModuleId = 3
                        },
                        new
                        {
                            PlanId = 5,
                            ModuleId = 4
                        },
                        new
                        {
                            PlanId = 5,
                            ModuleId = 5
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PlanId");

                    b.ToTable("Subscriptions");

                    b.HasData(
                        new
                        {
                            Id = 3001,
                            CustomerId = 2001,
                            EndDate = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlanId = 2,
                            StartDate = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3002,
                            CustomerId = 2002,
                            EndDate = new DateTime(2027, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlanId = 3,
                            StartDate = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3003,
                            CustomerId = 2003,
                            EndDate = new DateTime(2026, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlanId = 4,
                            StartDate = new DateTime(2025, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3004,
                            CustomerId = 2004,
                            EndDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlanId = 1,
                            StartDate = new DateTime(2025, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        },
                        new
                        {
                            Id = 3005,
                            CustomerId = 2005,
                            EndDate = new DateTime(2027, 2, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PlanId = 5,
                            StartDate = new DateTime(2026, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Active"
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MaxUsers = 5,
                            MonthlyPrice = 29m,
                            PlanName = "Starter"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MaxUsers = 20,
                            MonthlyPrice = 79m,
                            PlanName = "Growth"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MaxUsers = 50,
                            MonthlyPrice = 149m,
                            PlanName = "Professional"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            MaxUsers = 150,
                            MonthlyPrice = 299m,
                            PlanName = "Scale"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            MaxUsers = 500,
                            MonthlyPrice = 599m,
                            PlanName = "Enterprise"
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.UsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiRequestsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StorageUsedMb")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("UsageRecords");

                    b.HasData(
                        new
                        {
                            Id = 5001,
                            ApiRequestsCount = 3420,
                            CustomerId = 2001,
                            LogDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StorageUsedMb = 15360m
                        },
                        new
                        {
                            Id = 5002,
                            ApiRequestsCount = 8750,
                            CustomerId = 2002,
                            LogDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StorageUsedMb = 28160m
                        },
                        new
                        {
                            Id = 5003,
                            ApiRequestsCount = 15120,
                            CustomerId = 2003,
                            LogDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StorageUsedMb = 65280m
                        },
                        new
                        {
                            Id = 5004,
                            ApiRequestsCount = 950,
                            CustomerId = 2004,
                            LogDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StorageUsedMb = 3840m
                        },
                        new
                        {
                            Id = 5005,
                            ApiRequestsCount = 23890,
                            CustomerId = 2005,
                            LogDate = new DateTime(2026, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            StorageUsedMb = 121000m
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Admin", b =>
                {
                    b.HasBaseType("EmreGeydirenler_Lab2.Models.BaseUser");

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Address = "Level 12, 200 George Street, Sydney NSW 2000",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "olivia.bennett@qutech.com",
                            FirstName = "Olivia",
                            LastName = "Bennett",
                            PhoneNumber = "+61 2 9001 1001",
                            AdminRole = "SuperAdmin",
                            Department = "Platform Operations",
                            Password = "Admin@123"
                        },
                        new
                        {
                            Id = 1002,
                            Address = "85 Collins Street, Melbourne VIC 3000",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "liam.carter@qutech.com",
                            FirstName = "Liam",
                            LastName = "Carter",
                            PhoneNumber = "+61 3 9001 1002",
                            AdminRole = "SupportAdmin",
                            Department = "Customer Success",
                            Password = "Support@123"
                        },
                        new
                        {
                            Id = 1003,
                            Address = "40 Adelaide Street, Brisbane QLD 4000",
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlotte.nguyen@qutech.com",
                            FirstName = "Charlotte",
                            LastName = "Nguyen",
                            PhoneNumber = "+61 7 9001 1003",
                            AdminRole = "SecurityAdmin",
                            Department = "Information Security",
                            Password = "Security@123"
                        },
                        new
                        {
                            Id = 1004,
                            Address = "27 St Georges Terrace, Perth WA 6000",
                            CreatedAt = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "noah.reed@qutech.com",
                            FirstName = "Noah",
                            LastName = "Reed",
                            PhoneNumber = "+61 8 9001 1004",
                            AdminRole = "BillingAdmin",
                            Department = "Finance Operations",
                            Password = "Billing@123"
                        },
                        new
                        {
                            Id = 1005,
                            Address = "15 Barangaroo Avenue, Sydney NSW 2000",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "amelia.foster@qutech.com",
                            FirstName = "Amelia",
                            LastName = "Foster",
                            PhoneNumber = "+61 2 9001 1005",
                            AdminRole = "ProductAdmin",
                            Department = "Product Management",
                            Password = "Product@123"
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Customer", b =>
                {
                    b.HasBaseType("EmreGeydirenler_Lab2.Models.BaseUser");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.ToTable("BaseUsers", t =>
                        {
                            t.Property("Password")
                                .HasColumnName("Customer_Password");
                        });

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new
                        {
                            Id = 2001,
                            Address = "48 Darling Drive, Pyrmont NSW 2009",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ethan.walker@harborfoods.com.au",
                            FirstName = "Ethan",
                            LastName = "Walker",
                            PhoneNumber = "+61 2 8012 1101",
                            CompanyName = "Harbor Foods Pty Ltd",
                            Password = "Customer@123",
                            TaxNumber = "ABN 34 567 890 123"
                        },
                        new
                        {
                            Id = 2002,
                            Address = "190 Flinders Street, Melbourne VIC 3000",
                            CreatedAt = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "sophie.mitchell@southernsteel.com.au",
                            FirstName = "Sophie",
                            LastName = "Mitchell",
                            PhoneNumber = "+61 3 8012 1102",
                            CompanyName = "Southern Steel Manufacturing Pty Ltd",
                            Password = "Customer@234",
                            TaxNumber = "ABN 45 678 901 234"
                        },
                        new
                        {
                            Id = 2003,
                            Address = "22 Eagle Street, Brisbane QLD 4000",
                            CreatedAt = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jack.thompson@meditrackhealth.com.au",
                            FirstName = "Jack",
                            LastName = "Thompson",
                            PhoneNumber = "+61 7 8012 1103",
                            CompanyName = "MediTrack Health Systems Pty Ltd",
                            Password = "Customer@345",
                            TaxNumber = "ABN 56 789 012 345"
                        },
                        new
                        {
                            Id = 2004,
                            Address = "90 Terrace Road, East Perth WA 6004",
                            CreatedAt = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "grace.evans@pacificfreight.com.au",
                            FirstName = "Grace",
                            LastName = "Evans",
                            PhoneNumber = "+61 8 8012 1104",
                            CompanyName = "Pacific Freight Logistics Pty Ltd",
                            Password = "Customer@456",
                            TaxNumber = "ABN 67 890 123 456"
                        },
                        new
                        {
                            Id = 2005,
                            Address = "101 Pitt Street, Sydney NSW 2000",
                            CreatedAt = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mason.parker@australadvisory.com.au",
                            FirstName = "Mason",
                            LastName = "Parker",
                            PhoneNumber = "+61 2 8012 1105",
                            CompanyName = "Austral Advisory Group Pty Ltd",
                            Password = "Customer@567",
                            TaxNumber = "ABN 78 901 234 567"
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.AccountSetting", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Customer", "Customer")
                        .WithOne("AccountSetting")
                        .HasForeignKey("EmreGeydirenler_Lab2.Models.AccountSetting", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.AuditTrail", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.BaseUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Invoice", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.PlanModule", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Module", "Module")
                        .WithMany("PlanModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmreGeydirenler_Lab2.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("PlanModules")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Subscription", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmreGeydirenler_Lab2.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.UsageRecord", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Customer", "Customer")
                        .WithMany("UsageRecords")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Module", b =>
                {
                    b.Navigation("PlanModules");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("PlanModules");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Customer", b =>
                {
                    b.Navigation("AccountSetting");

                    b.Navigation("Invoices");

                    b.Navigation("Subscriptions");

                    b.Navigation("UsageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
