// <auto-generated />
using System;
using EmreGeydirenler_Lab2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmreGeydirenler_Lab2.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260402070431_AddAdminPasswords")]
    partial class AddAdminPasswords
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.AccountSetting", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ReceiveEmailAlerts")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomerId");

                    b.ToTable("AccountSetting");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.AuditTrail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActionDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuditTrails");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.BaseUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BaseUsers");

                    b.HasDiscriminator<string>("UserType").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Module", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Modules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Automates recurring invoices, payment reminders, and ledger exports.",
                            ModuleName = "Billing Automation"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tracks leads, deal stages, and customer lifecycle activities.",
                            ModuleName = "CRM Pipeline"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Designs approval flows and task routing for internal processes.",
                            ModuleName = "Workflow Engine"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Provides KPI dashboards, cohort analysis, and custom reporting.",
                            ModuleName = "Analytics Hub"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Manages role-based permissions, SSO integration, and audit visibility.",
                            ModuleName = "Access Control"
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.PlanModule", b =>
                {
                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ModuleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PlanId", "ModuleId");

                    b.HasIndex("ModuleId");

                    b.ToTable("PlanModules");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PlanId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("PlanId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxUsers")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MonthlyPrice")
                        .HasColumnType("TEXT");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsActive = true,
                            MaxUsers = 5,
                            MonthlyPrice = 29m,
                            PlanName = "Starter"
                        },
                        new
                        {
                            Id = 2,
                            IsActive = true,
                            MaxUsers = 20,
                            MonthlyPrice = 79m,
                            PlanName = "Growth"
                        },
                        new
                        {
                            Id = 3,
                            IsActive = true,
                            MaxUsers = 50,
                            MonthlyPrice = 149m,
                            PlanName = "Professional"
                        },
                        new
                        {
                            Id = 4,
                            IsActive = true,
                            MaxUsers = 150,
                            MonthlyPrice = 299m,
                            PlanName = "Scale"
                        },
                        new
                        {
                            Id = 5,
                            IsActive = true,
                            MaxUsers = 500,
                            MonthlyPrice = 599m,
                            PlanName = "Enterprise"
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.UsageRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ApiRequestsCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LogDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("StorageUsedMb")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("UsageRecords");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Admin", b =>
                {
                    b.HasBaseType("EmreGeydirenler_Lab2.Models.BaseUser");

                    b.Property<string>("AdminRole")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 1001,
                            Address = "Maslak Mah. IT Plaza No:12, Istanbul",
                            CreatedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "aylin.demir@qutech.com",
                            FirstName = "Aylin",
                            LastName = "Demir",
                            PhoneNumber = "+90-212-555-0101",
                            AdminRole = "SuperAdmin",
                            Department = "Platform Operations",
                            Password = "Admin@123"
                        },
                        new
                        {
                            Id = 1002,
                            Address = "Levent Mah. Teknoloji Cad. No:8, Istanbul",
                            CreatedAt = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mert.kara@qutech.com",
                            FirstName = "Mert",
                            LastName = "Kara",
                            PhoneNumber = "+90-212-555-0102",
                            AdminRole = "SupportAdmin",
                            Department = "Customer Success",
                            Password = "Support@123"
                        },
                        new
                        {
                            Id = 1003,
                            Address = "Cankaya Mah. Is Merkezi No:4, Ankara",
                            CreatedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "selin.yilmaz@qutech.com",
                            FirstName = "Selin",
                            LastName = "Yilmaz",
                            PhoneNumber = "+90-312-555-0103",
                            AdminRole = "SecurityAdmin",
                            Department = "Information Security",
                            Password = "Security@123"
                        },
                        new
                        {
                            Id = 1004,
                            Address = "Alsancak Mah. Inovasyon Sok. No:19, Izmir",
                            CreatedAt = new DateTime(2024, 4, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "can.aydin@qutech.com",
                            FirstName = "Can",
                            LastName = "Aydin",
                            PhoneNumber = "+90-232-555-0104",
                            AdminRole = "BillingAdmin",
                            Department = "Finance Operations",
                            Password = "Billing@123"
                        },
                        new
                        {
                            Id = 1005,
                            Address = "Atasehir Mah. Startup Cad. No:22, Istanbul",
                            CreatedAt = new DateTime(2024, 5, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ece.sahin@qutech.com",
                            FirstName = "Ece",
                            LastName = "Sahin",
                            PhoneNumber = "+90-216-555-0105",
                            AdminRole = "ProductAdmin",
                            Department = "Product Management",
                            Password = "Product@123"
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Customer", b =>
                {
                    b.HasBaseType("EmreGeydirenler_Lab2.Models.BaseUser");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new
                        {
                            Id = 2001,
                            Address = "Beylikduzu OSB 2. Cad. No:45, Istanbul",
                            CreatedAt = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "burak.celik@novafoods.com",
                            FirstName = "Burak",
                            LastName = "Celik",
                            PhoneNumber = "+90-212-555-1101",
                            CompanyName = "Nova Foods A.S.",
                            TaxNumber = "TR3456789012"
                        },
                        new
                        {
                            Id = 2002,
                            Address = "Nilufer Sanayi Bolgesi No:77, Bursa",
                            CreatedAt = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "zeynep.arslan@metallink.com",
                            FirstName = "Zeynep",
                            LastName = "Arslan",
                            PhoneNumber = "+90-224-555-1102",
                            CompanyName = "MetalLink Manufacturing Ltd.",
                            TaxNumber = "TR4567890123"
                        },
                        new
                        {
                            Id = 2003,
                            Address = "ODTU Teknokent A Blok No:9, Ankara",
                            CreatedAt = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kerem.toprak@medisync.io",
                            FirstName = "Kerem",
                            LastName = "Toprak",
                            PhoneNumber = "+90-312-555-1103",
                            CompanyName = "MediSync Health Tech",
                            TaxNumber = "TR5678901234"
                        },
                        new
                        {
                            Id = 2004,
                            Address = "Kemalpasa Lojistik Merkezi No:31, Izmir",
                            CreatedAt = new DateTime(2024, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elif.tas@logiroad.com",
                            FirstName = "Elif",
                            LastName = "Tas",
                            PhoneNumber = "+90-232-555-1104",
                            CompanyName = "LogiRoad Logistics",
                            TaxNumber = "TR6789012345"
                        },
                        new
                        {
                            Id = 2005,
                            Address = "Kadikoy Finans Merkezi No:14, Istanbul",
                            CreatedAt = new DateTime(2024, 5, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "onur.gunes@finpeak.co",
                            FirstName = "Onur",
                            LastName = "Gunes",
                            PhoneNumber = "+90-216-555-1105",
                            CompanyName = "FinPeak Advisory",
                            TaxNumber = "TR7890123456"
                        });
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.AccountSetting", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Customer", "Customer")
                        .WithOne("AccountSetting")
                        .HasForeignKey("EmreGeydirenler_Lab2.Models.AccountSetting", "CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.AuditTrail", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.BaseUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Invoice", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.PlanModule", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Module", "Module")
                        .WithMany("PlanModules")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmreGeydirenler_Lab2.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("PlanModules")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Subscription", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Customer", "Customer")
                        .WithMany("Subscriptions")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EmreGeydirenler_Lab2.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany("Subscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.UsageRecord", b =>
                {
                    b.HasOne("EmreGeydirenler_Lab2.Models.Customer", "Customer")
                        .WithMany("UsageRecords")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Module", b =>
                {
                    b.Navigation("PlanModules");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.SubscriptionPlan", b =>
                {
                    b.Navigation("PlanModules");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("EmreGeydirenler_Lab2.Models.Customer", b =>
                {
                    b.Navigation("AccountSetting");

                    b.Navigation("Invoices");

                    b.Navigation("Subscriptions");

                    b.Navigation("UsageRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
